import type { Chapter, ChapterEvent } from "./types";

export function ChapterEventsStage({ chapters, total, selectedId, text, events, busy, onSelect }: { chapters: Chapter[]; total: number; selectedId?: string; text: string; events: ChapterEvent[]; busy: boolean; onSelect: (id: string) => void }) {
  return <div className="grid min-h-[calc(100vh-344px)] grid-cols-[minmax(230px,.72fr)_minmax(480px,1.45fr)_minmax(360px,1fr)] max-md:grid-cols-1">
    <section className="min-w-0 border-r border-[var(--border-subtle)] max-md:border-r-0 max-md:border-b" aria-labelledby="production-chapters-heading">
      <div className="flex h-12 items-center justify-between border-b border-[var(--border-subtle)] px-4"><h2 id="production-chapters-heading" className="text-xs font-bold tracking-wider">章节范围</h2><span className="font-mono text-[10px] text-[var(--fg-tertiary)]">{chapters.length}/{total}</span></div>
      <div className="max-h-[calc(100vh-392px)] overflow-y-auto p-2">{chapters.map((chapter) => <button key={chapter.id} type="button" disabled={busy} className={`flex min-h-11 w-full items-center gap-3 rounded px-3 text-left hover:bg-[var(--bg-subtle)] ${selectedId === chapter.id ? "bg-[var(--bg-subtle)] ring-1 ring-[var(--border-strong)]" : ""}`} onClick={() => onSelect(chapter.id)}><span className="font-mono text-[10px] text-[var(--fg-tertiary)]">{String(chapter.chapter_index + 1).padStart(3, "0")}</span><span className="truncate text-sm">{chapter.title}</span></button>)}</div>
    </section>
    <section className="min-w-0 border-r border-[var(--border-subtle)] p-[clamp(26px,4vw,52px)] max-md:border-r-0 max-md:border-b" aria-labelledby="events-heading">
      <p className="mb-2 font-mono text-[11px] font-semibold tracking-[.17em] text-[var(--accent)]">STRUCTURED EVIDENCE</p><h2 id="events-heading" className="m-0 max-w-3xl font-serif text-[clamp(28px,3.6vw,50px)] font-semibold leading-[1.13] tracking-[-.04em]">章节事件是后续生产的证据索引。</h2><p className="my-6 max-w-3xl text-sm leading-7 text-[var(--fg-secondary)]">先核对人物、地点、冲突、转折和线索，再进入故事弧；所有改编必须能回到原文字节范围。</p>
      <div className="border-t border-[var(--border-subtle)]">{events.map((event) => <article className="grid grid-cols-[92px_minmax(0,1fr)_auto] gap-4 border-b border-[var(--border-subtle)] py-4" key={event.id}><span className="font-mono text-[10px] tracking-wider text-[var(--accent)]">{event.type}</span><div><strong className="text-[13px]">事件 {event.occurrence + 1}</strong><pre className="mt-2 max-h-32 overflow-auto whitespace-pre-wrap font-mono text-xs leading-5 text-[var(--fg-secondary)]">{JSON.stringify(event.payload, null, 2)}</pre></div><small className="text-[11px] text-[var(--fg-tertiary)]">{event.sources.length} 段证据</small></article>)}{selectedId && !events.length && !busy ? <p className="m-7 text-[13px] text-[var(--fg-tertiary)]">本章还没有结构化事件。生成与人工校对入口将在本阶段继续接通。</p> : null}{!selectedId ? <p className="m-7 text-[13px] text-[var(--fg-tertiary)]">选择章节后查看结构化事件和原文证据。</p> : null}</div>
    </section>
    <section className="min-w-0 bg-[color-mix(in_srgb,var(--bg-surface)_86%,var(--bg-canvas))]" aria-labelledby="production-evidence-heading"><div className="flex h-12 items-center justify-between border-b border-[var(--border-subtle)] px-4"><h2 id="production-evidence-heading" className="text-xs font-bold tracking-wider">原文证据</h2><span className="font-mono text-[10px] text-[var(--fg-tertiary)]">READ ONLY</span></div><pre className="m-0 max-h-[calc(100vh-392px)] overflow-auto whitespace-pre-wrap p-[clamp(20px,4vw,44px)] font-serif text-[15px] leading-8 text-[var(--fg-secondary)]">{text || "选择章节后在此查看原文。"}</pre></section>
  </div>;
}
