import type { Chapter, ChapterEvent } from "../types";
import { useEpisodeWorkspace } from "./use-episode-workspace";

function eventSummary(event: ChapterEvent) {
  return Object.values(event.payload).filter(Boolean).join(" → ") || event.type;
}

export function EpisodeStage({ seriesId, episodeIndex, chapter, events, chapterCount, chapterTotal, busy, setBusy, setStatus, onEpisodeChange }: { seriesId: string; episodeIndex: number; chapter?: Chapter; events: ChapterEvent[]; chapterCount: number; chapterTotal: number; busy: boolean; setBusy: (busy: boolean) => void; setStatus: (message: string) => void; onEpisodeChange: (index: number) => void }) {
  const state = useEpisodeWorkspace({ seriesId, episodeIndex, busy, setBusy, setStatus });
  const selected = new Set(state.draft.sourceEventIds);
  function toggleSource(id: string) {
    state.updateDraft({ sourceEventIds: selected.has(id) ? state.draft.sourceEventIds.filter((item) => item !== id) : [...state.draft.sourceEventIds, id] });
  }

  return <div className="grid min-h-[calc(100vh-344px)] grid-cols-[minmax(250px,.75fr)_minmax(480px,1.35fr)_minmax(360px,1fr)] max-md:grid-cols-1">
    <section className="border-r border-[var(--border-subtle)] p-6 max-md:border-r-0 max-md:border-b" aria-labelledby="episode-sources-heading">
      <div className="mb-5 flex items-end gap-3"><label className="text-xs text-[var(--fg-secondary)]">分集序号<input aria-label="分集序号" type="number" min={1} step={1} disabled={busy} value={episodeIndex} onChange={(event) => { const value = Number(event.target.value); if (Number.isSafeInteger(value) && value > 0) onEpisodeChange(value); }} className="mt-1 block w-28 rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-2 font-mono text-sm" /></label><span className="pb-2 text-[11px] text-[var(--fg-tertiary)]">URL 可恢复</span></div>
      <h2 id="episode-sources-heading" className="text-xs font-bold tracking-wider">当前章节事件</h2><p className="my-3 text-xs leading-6 text-[var(--fg-tertiary)]">{chapter ? `${chapter.title} · ${events.length} 个事件` : "先在章节事件阶段选择章节"}。当前仅加载前 {chapterCount} 章{chapterTotal > chapterCount ? `，全书共 ${chapterTotal} 章` : ""}。</p>
      <div className="space-y-2">{events.map((event) => <label key={event.id} className="flex cursor-pointer gap-3 rounded border border-[var(--border-subtle)] p-3 text-sm"><input type="checkbox" disabled={busy} checked={selected.has(event.id)} onChange={() => toggleSource(event.id)} /><span><b className="block text-xs">{event.type}</b><span className="text-[var(--fg-secondary)]">{eventSummary(event)}</span></span></label>)}</div>
      {!events.length ? <p className="mt-5 text-sm text-[var(--fg-tertiary)]">当前章节没有可选事件；先完成章节事件首版。</p> : null}
    </section>
    <section className="border-r border-[var(--border-subtle)] p-[clamp(26px,4vw,52px)] max-md:border-r-0 max-md:border-b" aria-labelledby="episode-editor-heading">
      <p className="mb-2 font-mono text-[11px] font-semibold tracking-[.17em] text-[var(--accent)]">EPISODE ARC</p><h2 id="episode-editor-heading" className="m-0 font-serif text-[clamp(30px,4vw,54px)] font-semibold leading-none tracking-[-.045em]">第 {episodeIndex} 集首版</h2>
      <div className="mt-8 space-y-4"><label className="block text-xs text-[var(--fg-secondary)]">标题<input disabled={busy} value={state.draft.title} onChange={(event) => state.updateDraft({ title: event.target.value })} className="mt-1 block w-full rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-3 text-sm" /></label><label className="block text-xs text-[var(--fg-secondary)]">故事弧<textarea disabled={busy} rows={7} value={state.draft.storyArc} onChange={(event) => state.updateDraft({ storyArc: event.target.value })} className="mt-1 block w-full rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-3 text-sm leading-6" /></label><label className="block text-xs text-[var(--fg-secondary)]">目标时长（180–300 秒）<input type="number" min={180} max={300} disabled={busy} value={state.draft.targetDurationSeconds} onChange={(event) => state.updateDraft({ targetDurationSeconds: Number(event.target.value) })} className="mt-1 block w-full rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-3 text-sm" /></label><label className="block text-xs text-[var(--fg-secondary)]">前情回顾（可选）<textarea disabled={busy} rows={3} value={state.draft.recap} onChange={(event) => state.updateDraft({ recap: event.target.value })} className="mt-1 block w-full rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-3 text-sm" /></label><label className="block text-xs text-[var(--fg-secondary)]">下集钩子（可选）<textarea disabled={busy} rows={3} value={state.draft.nextHook} onChange={(event) => state.updateDraft({ nextHook: event.target.value })} className="mt-1 block w-full rounded border border-[var(--border-subtle)] bg-[var(--bg-canvas)] p-3 text-sm" /></label><button type="button" disabled={busy} onClick={() => void state.save()} className="rounded bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "处理中…" : "保存并回读持久证据"}</button></div>
    </section>
    <section className="bg-[color-mix(in_srgb,var(--bg-surface)_86%,var(--bg-canvas))]" aria-labelledby="episode-evidence-heading"><div className="flex h-12 items-center justify-between border-b border-[var(--border-subtle)] px-4"><h2 id="episode-evidence-heading" className="text-xs font-bold tracking-wider">持久证据快照</h2><span className="font-mono text-[10px] text-[var(--fg-tertiary)]">READ ONLY</span></div><div className="space-y-4 p-6">{state.episode?.sources.map((source) => <article key={source.sourceIndex} className="border-b border-[var(--border-subtle)] pb-4"><p className="font-mono text-[10px] text-[var(--fg-tertiary)]">{source.chapterId} · {source.byteStart}–{source.byteEnd}</p><p className="my-2 text-sm leading-6">{source.sourceText}</p><p className="break-all font-mono text-[9px] text-[var(--fg-tertiary)]">SHA-256 {source.sourceHash}</p></article>)}{!state.episode ? <p className="text-sm leading-7 text-[var(--fg-tertiary)]">该分集尚无持久记录。保存后这里显示服务端重新读取并校验过的原文快照。</p> : !state.episode.sources.length ? <p className="text-sm text-[var(--fg-tertiary)]">持久记录没有证据快照。</p> : null}</div></section>
  </div>;
}
